name: TpsBar
version: '${project.version}'
main: cn.paper_card.tps_bar.TpsBar
api-version: 1.20
author: Paper99
folia-supported: true

commands:
  tps-bar:
    permission: tps-bar.command

permissions:
  tps-bar.command:
    default: true

